package org.metalib.papifly.fx.login;

public enum AuthErrorCode {
    NETWORK_ERROR,
    USER_CANCELLED,
    CALLBACK_TIMEOUT,
    STATE_MISMATCH,
    TOKEN_EXCHANGE_FAILED,
    TOKEN_VALIDATION_FAILED,
    REFRESH_FAILED,
    PROVIDER_NOT_REGISTERED,
    DEVICE_FLOW_NOT_SUPPORTED,
    DEVICE_FLOW_TIMEOUT,
    SECRET_STORE_FAILURE
}
